
/* Drop Tables */

DROP TABLE GATE_SLOT_RESERVATIONS;
DROP TABLE ORDERS;
DROP TABLE CARRIER_SESSIONS;
DROP TABLE CARRIERS;
DROP TABLE GATES;
DROP TABLE WAREHOUSES;




/* Create Tables */

CREATE TABLE CARRIERS
(
	CARRIER_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1) ,
	NAME varchar(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(30) NOT NULL WITH DEFAULT 'unter',
	PRIMARY KEY (CARRIER_ID)
) ORGANIZE BY ROW;

CREATE TABLE CARRIER_SESSIONS
(
	CARRIER_SESSION_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1),
	CARRIER_ID bigint NOT NULL,
	SESSION_ID varchar(36) NOT NULL,
	PRIMARY KEY (CARRIER_SESSION_ID)
) ORGANIZE BY ROW;

CREATE TABLE GATES
(
	GATE_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1) ,
	WAREHOUSE_ID bigint NOT NULL,
	NAME varchar(100) NOT NULL UNIQUE,
	PRIMARY KEY (GATE_ID)
) ORGANIZE BY ROW;


CREATE TABLE GATE_SLOT_RESERVATIONS
(
	GATE_SLOT_RESERVATION_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1) ,
	RESERVATION_NUMBER varchar(36) NOT NULL UNIQUE,
	ORDER_ID bigint NOT NULL,
	GATE_ID bigint NOT NULL,
	LOAD_DATE date NOT NULL,
	FROM_TIME time NOT NULL,
	TILL_TIME time NOT NULL,
	REFERENCE varchar(100),
	NUMBER_PLATE varchar(100),
	DRIVER_NAME varchar(100),
	VEHICLE_TYPE varchar(100),
	PRIMARY KEY (GATE_SLOT_RESERVATION_ID)
) ORGANIZE BY ROW;




CREATE TABLE ORDERS
(
	ORDER_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1),
	ORDER_NUMBER varchar(36) NOT NULL UNIQUE,
	CARRIER_ID bigint NOT NULL,
	PRIMARY KEY (ORDER_ID)
) ORGANIZE BY ROW;


CREATE TABLE WAREHOUSES
(
	WAREHOUSE_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1),
	NAME varchar(100) NOT NULL UNIQUE,
	PRIMARY KEY (WAREHOUSE_ID)
) ORGANIZE BY ROW;



/* Create Foreign Keys */

ALTER TABLE ORDERS
	ADD FOREIGN KEY (CARRIER_ID)
	REFERENCES CARRIERS (CARRIER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
	NOT ENFORCED
;

ALTER TABLE CARRIER_SESSIONS
	ADD FOREIGN KEY (CARRIER_ID)
	REFERENCES CARRIERS (CARRIER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
	NOT ENFORCED
;

ALTER TABLE GATE_SLOT_RESERVATIONS
	ADD FOREIGN KEY (GATE_ID)
	REFERENCES GATES (GATE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
	NOT ENFORCED
;


ALTER TABLE GATE_SLOT_RESERVATIONS
	ADD FOREIGN KEY (ORDER_ID)
	REFERENCES ORDERS (ORDER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
	NOT ENFORCED
;


ALTER TABLE GATES
	ADD FOREIGN KEY (WAREHOUSE_ID)
	REFERENCES WAREHOUSES (WAREHOUSE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
	NOT ENFORCED
;

INSERT INTO WAREHOUSES (NAME) VALUES ('WH-UBER-1');
INSERT INTO WAREHOUSES (NAME) VALUES ('WH-UNTER-1');
INSERT INTO CARRIERS (NAME) VALUES ('UNTER-1');
INSERT INTO GATES (WAREHOUSE_ID, NAME) VALUES (1, 'GATE-1');
INSERT INTO GATES (WAREHOUSE_ID, NAME) VALUES (1, 'GATE-2');
INSERT INTO GATES (WAREHOUSE_ID, NAME) VALUES (1, 'GATE-3');
INSERT INTO GATES (WAREHOUSE_ID, NAME) VALUES (1, 'GATE-4');
INSERT INTO GATES (WAREHOUSE_ID, NAME) VALUES (1, 'GATE-5');
INSERT INTO GATES (WAREHOUSE_ID, NAME) VALUES (2, 'GATE-U-1');
INSERT INTO GATES (WAREHOUSE_ID, NAME) VALUES (2, 'GATE-U-2');
INSERT INTO GATES (WAREHOUSE_ID, NAME) VALUES (2, 'GATE-U-3');
INSERT INTO ORDERS (ORDER_NUMBER, CARRIER_ID) VALUES (1, 1);
INSERT INTO ORDERS (ORDER_NUMBER, CARRIER_ID) VALUES (2, 1);
INSERT INTO ORDERS (ORDER_NUMBER, CARRIER_ID) VALUES (3, 2);
INSERT INTO GATE_SLOT_RESERVATIONS (RESERVATION_NUMBER, ORDER_ID, GATE_ID, LOAD_DATE, FROM_TIME, TILL_TIME) values (1, 1, 2, DATE('2016-07-01'), TIME('12:00:00'), TIME('13:00:00'));
INSERT INTO GATE_SLOT_RESERVATIONS (RESERVATION_NUMBER, ORDER_ID, GATE_ID, LOAD_DATE, FROM_TIME, TILL_TIME) values (2, 3, 1, DATE('2016-07-01'), TIME('14:00:00'), TIME('15:00:00'));
INSERT INTO GATE_SLOT_RESERVATIONS (RESERVATION_NUMBER, ORDER_ID, GATE_ID, LOAD_DATE, FROM_TIME, TILL_TIME) values (3, 2, 3, DATE('2016-07-01'), TIME('12:00:00'), TIME('13:00:00'));
INSERT INTO GATE_SLOT_RESERVATIONS (RESERVATION_NUMBER, ORDER_ID, GATE_ID, LOAD_DATE, FROM_TIME, TILL_TIME) values (4, 2, 4, DATE('2016-07-01'), TIME('12:00:00'), TIME('13:00:00'));


