
/* Drop Tables */

DROP TABLE GATE_SLOT_RESERVATIONS;
DROP TABLE ORDERS;
DROP TABLE CARRIER_SESSIONS;
DROP TABLE CARRIERS;
DROP TABLE GATES;
DROP TABLE WAREHOUSES;




/* Create Tables */

CREATE TABLE CARRIERS
(
	CARRIER_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1) ,
	NAME varchar(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(30) NOT NULL WITH DEFAULT 'unter',
	PRIMARY KEY (CARRIER_ID)
) ORGANIZE BY ROW;

CREATE TABLE CARRIER_SESSIONS
(
	CARRIER_SESSION_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1),
	CARRIER_ID bigint NOT NULL,
	SESSION_ID varchar(36) NOT NULL,
	PRIMARY KEY (CARRIER_SESSION_ID)
) ORGANIZE BY ROW;

CREATE TABLE GATES
(
	GATE_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1) ,
	WAREHOUSE_ID bigint NOT NULL,
	NAME varchar(100) NOT NULL UNIQUE,
	PRIMARY KEY (GATE_ID)
) ORGANIZE BY ROW;


CREATE TABLE GATE_SLOT_RESERVATIONS
(
	GATE_SLOT_RESERVATION_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1) ,
	RESERVATION_NUMBER varchar(36) NOT NULL UNIQUE,
	ORDER_ID bigint NOT NULL,
	GATE_ID bigint NOT NULL,
	LOAD_DATE date NOT NULL,
	FROM_TIME time NOT NULL,
	TILL_TIME time NOT NULL,
	PRIMARY KEY (GATE_SLOT_RESERVATION_ID)
) ORGANIZE BY ROW;


CREATE TABLE ORDERS
(
	ORDER_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1),
	ORDER_NUMBER varchar(36) NOT NULL UNIQUE,
	CARRIER_ID bigint NOT NULL,
	PRIMARY KEY (ORDER_ID)
) ORGANIZE BY ROW;


CREATE TABLE WAREHOUSES
(
	WAREHOUSE_ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1),
	NAME varchar(100) NOT NULL UNIQUE,
	PRIMARY KEY (WAREHOUSE_ID)
) ORGANIZE BY ROW;



/* Create Foreign Keys */

ALTER TABLE ORDERS
	ADD FOREIGN KEY (CARRIER_ID)
	REFERENCES CARRIERS (CARRIER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
	NOT ENFORCED
;

ALTER TABLE CARRIER_SESSIONS
	ADD FOREIGN KEY (CARRIER_ID)
	REFERENCES CARRIERS (CARRIER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
	NOT ENFORCED
;

ALTER TABLE GATE_SLOT_RESERVATIONS
	ADD FOREIGN KEY (GATE_ID)
	REFERENCES GATES (GATE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
	NOT ENFORCED
;


ALTER TABLE GATE_SLOT_RESERVATIONS
	ADD FOREIGN KEY (ORDER_ID)
	REFERENCES ORDERS (ORDER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
	NOT ENFORCED
;


ALTER TABLE GATES
	ADD FOREIGN KEY (WAREHOUSE_ID)
	REFERENCES WAREHOUSES (WAREHOUSE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
	NOT ENFORCED
;



